anothersite/anothersite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path('api/', include('myapiapp.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('shop/', include('shopapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('myauth/', include('myauth.urls')),


    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += i18n_patterns(


    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

anothersite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UserProfileView,
    UserListView,
    ChangeAvatarView,
    HelloView,



)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),

    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),
    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
    path('user_list/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserProfileView.as_view(), name='user-profile'),
    path('change_avatar/<int:pk>/', ChangeAvatarView.as_view(), name='change_avatar')
]

anothersite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models



def user_avatar_directory_path(instance: 'Profile', filename: str) -> str:
    return 'profile/profile_{pk}/avatar/{filename}'.format(
        pk=instance.user.pk,
        filename=filename,
    )

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=user_avatar_directory_path)

anothersite/myauth/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import Group
from .models import Profile




class ProfileForm(forms.ModelForm):
    class Meta:
       model = Profile
       fields = 'user', 'bio', 'agreement_accepted', 'avatar',

anothersite/myauth/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from .models import Profile
from django.utils.translation import gettext_lazy as _
from random import random



class HelloView(View):
    welcome_message = _('welcome hello world!')
    def get(self, request: HttpRequest) -> HttpResponse:

        return HttpResponse(f'<h1>{self.welcome_message}<h1/>')
class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"

class UserProfileView(DetailView):
    template_name = 'myauth/user_profile.html'
    model = User
    context_object_name = 'user'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['pk']
        context['user'] = User.objects.get(pk=user_id)
        return context

class ChangeAvatarView(UpdateView, UserPassesTestMixin):
    model = Profile
    fields = 'avatar',
    template_name_suffix = '_update_form'

    def test_func(self):
        if self.request.user.is_staff:
            return True
        obj = self.get_object()
        return obj.user == self.request.use



    def get_success_url(self):
        return reverse(
            'myauth:user-profile',
            kwargs={'pk': self.object.user.pk},
        )





class UserListView(ListView):
    template_name = 'myauth/user_list.html'
    model = User
    context_object_name = 'users'



class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response



class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response

@cache_page(60*2)
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r} + {random()}")



@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse("Session set!")


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("foobar", "default")
    return HttpResponse(f"Session value: {value!r}")

class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({'foo': 'bar', 'spam': 'eggs'})

anothersite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}
{% block title %}
   About me
{% endblock %}

{% block body %}
   <h1>User info</h1>
       <div>
           Products available: {% now 'u' %}
       </div>
       {% if user.is_authenticated %}
         {% cache 300 userinfo user.username %}
          <h2>Detail</h2>
          {% if user.profile.avatar %}
          <img src = '{{ user.profile.avatar.url }}' alt="{{ user.profile.avatar.name }}">
       {% else %}
        avatar is not loaded
       {% endif %}
          <div>
         <a href="{% url 'myauth:change_avatar' pk=user.profile.pk %}">Change Avatar</a>
          </div>
          <p>Username: {{ user.username }}</p>
          <p>Firstname: {{ user.first_name }}</p>
          <p>Last name: {{ user.last_name }}</p>
          <p>Email: {{ user.email }}</p>
          <p>Bio: {{ user.profile.bio }}</p>
          {% endcache %}
       {% else %}
            <h2>User is anonymous</h2>
       {% endif %}
{% endblock %}

anothersite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

      {% endblock %}</title>
</head>
<body>
 {% block body %}

 {% endblock %}
</body>
</html>

anothersite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
   Login
{% endblock %}

{% block body %}
   <form method="post">
       {% csrf_token %}

       {{ form.as_p }}

       <button type='submit'>Login</button>
   </form>
{% endblock %}

anothersite/myauth/templates/myauth/profile_update_form.html
{% extends 'myauth/base.html' %}

{% block title %}
   Update
{% endblock %}

{% block body %}
   <h1>Change Avatar</h1>

   <form method="post" enctype="multipart/form-data">
       {% csrf_token %}
       {{ form.as_p }}
       <input type='submit' value="Change">
   </form>
{% endblock %}

anothersite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
   Register
{% endblock %}

{% block body %}
   <h1>Register</h1>
   <form method="post">
       {% csrf_token %}
       {{ form.as_p }}
       <input type='submit' value="Register">
   </form>
{% endblock %}

anothersite/myauth/templates/myauth/user_list.html
{% extends 'myauth/base.html' %}

{% block title %}
   Users
{% endblock %}

{% block body %}
   <h1>Users:</h1>

   <div>
       {% for user in users %}
           <div>

       {% if user.profile.avatar %}
          <img src = '{{ user.profile.avatar.url }}' alt="{{ user.profile.avatar.name }}">
       {% else %}
        avatar is not loaded
       {% endif %}

               <p>Username: <a href="{% url 'myauth:user-profile' user.pk %}">{{ user.username }}</a></p>
           </div>
       {% empty %}
           <p>No users found.</p>
       {% endfor %}
   </div>
{% endblock %}

anothersite/myauth/templates/myauth/user_profile.html
{% extends 'myauth/base.html' %}

{% block title %}
   Profile: {{ user.username }}
{% endblock %}

{% block body %}
   <div>
       {% if user.profile.avatar %}
          <img src = '{{ user.profile.avatar.url }}' alt="{{ user.profile.avatar.name }}">
       {% else %}
        avatar is not loaded
       {% endif %}
       {% if request.user.is_staff or request.user.pk == user.pk  %}
          <div>
         <a href="{% url 'myauth:change_avatar' pk=user.profile.pk %}">Change Avatar</a>
          </div>
      {% endif %}
          <p>Username: {{ user.username }}</p>
          <p>Firstname: {{ user.first_name }}</p>
          <p>Last name: {{ user.last_name }}</p>
          <p>Email: {{ user.email }}</p>
          <p>Bio: {{ user.profile.bio }}</p>
       <div>
         <a href="{% url 'myauth:user-list'%}">Back to user list </a>
      </div>
    </div>
{% endblock %}ml>