anothersite/anothersite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from django.contrib.sitemaps.views import sitemap

from .sitemaps import sitemaps

urlpatterns = [
    path('api/', include('myapiapp.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('shop/', include('shopapp.urls')),
    path('blog/', include('blogapp.urls')),
    path('myauth/', include('myauth.urls')),


    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns += i18n_patterns(


    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    )
    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

anothersite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    UserProfileView,
    UserListView,
    ChangeAvatarView,
    HelloView,



)

app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),

    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),

    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),

    path("session/set/", set_session_view, name="session-set"),
    path("session/get/", get_session_view, name="session-get"),
    path('foo-bar/', FooBarView.as_view(), name='foo-bar'),
    path('user_list/', UserListView.as_view(), name='user-list'),
    path('user/<int:pk>/', UserProfileView.as_view(), name='user-profile'),
    path('change_avatar/<int:pk>/', ChangeAvatarView.as_view(), name='change_avatar')
]

anothersite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.views.decorators.cache import cache_page
from .views import (
    GroupListView,
    OrdersListView,
    ProductCreateView,
    OrderCreateView,
    ShopIndexView,
    ProductListViews,
    ProductDetailsView,
    OrderDetailView,
    ProductUpdateView,
    ProductDeleteView,
    OrderDeleteView,
    OrderUpdateView,
    ProductsDataExportView,
    OrdersDataExportView,
    ProductViewSet,
    OrderViewSet,
    LatestProductsFeed,
    UserOrdersListView,
    UserOrdersExport,

)


app_name = 'shopapp'
routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)

urlpatterns = [
    path('api/', include(routers.urls)),
    path("", ShopIndexView.as_view(), name='Index'),
    path("groups/", GroupListView.as_view(), name="groups_list"),
    path("products/", ProductListViews.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archived/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path('orders/create/', OrderCreateView.as_view(), name='order_create'),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    path("products/export", ProductsDataExportView.as_view(), name="products_export"),
    path("orders/export", OrdersDataExportView.as_view(), name="orders_export"),
    path("products/latest/feed/", LatestProductsFeed(), name="products-latest"),
    path('user/<int:user_id>/orders/', UserOrdersListView.as_view(), name='user_orders'),
    path("users/<int:user_id>/orders/export/", UserOrdersExport.as_view(), name='user_orders_export'),
]

anothersite/shopapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import Group
from .models import Product, Order




class ProductForm(forms.ModelForm):
    class Meta:
       model = Product
       fields = 'name', 'price', 'description', 'discount', 'preview'

    images = forms.ImageField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
    )




class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = 'delivery_address', 'promocode', 'products', 'user'


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = 'name',



class CSVImportForm(forms.Form):
    csv_file = forms.FileField()

anothersite/shopapp/views.py
"""
Модуль содерждит различные наборы представлений.

View интернет-магазина: по товарам, заказам и т.д.

"""
import logging
from timeit import default_timer
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.models import Group, User
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from csv import DictWriter
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from rest_framework.parsers import MultiPartParser
from rest_framework.response import Response
from django.utils.decorators import method_decorator

from .forms import ProductForm,  GroupForm
from .models import Product, Order, ProductImage
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
from rest_framework.decorators import action
from rest_framework.request import Request
from .common import save_csv_products
from django.contrib.gis.feeds import Feed
from django.core.cache import cache


log = logging.getLogger(__name__)
@extend_schema(description='Product views CRUD')
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = [
        'name',
        'description',
    ]
    filterset_fields = [
        'name',
        'description',
        'price',
        'discount',
        'archived',
    ]
    ordering_fields = [
        'pk',
        'price',
    ]
    @extend_schema(
        summary='Get one product by ID',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description='Empty response, product by id not found'),
        }
    )
    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):
        return super().list(*args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
         return super().retrieve(*args, **kwargs)

    @action(methods=['get'], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content='text/csv')
        filename = 'product-export.csv'
        response['content-Disposition'] = f'attachment; filename ={filename}'
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            'name',
            'description',
            'price',
            'discount',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()
        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response
    @action(
        detail=False,
        methods=['post'],
        parser_classes=[MultiPartParser],

    )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES['file'].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)

class LatestProductsFeed(Feed):
    title = 'Shop products(latest)'
    description = 'Updates on changes and addition shop products'
    link = reverse_lazy('shopapp:products_list')

    def items(self):
        return (
            Product.objects
            .filter(archived=False)
            .order_by('-created_at')[:5]
        )

    def item_title(self, item: Product):
        return item.name

    def item_description(self, item: Product):
        return item.description[:200]

    def item_link(self, item: Product):
        return reverse('shopapp:product_details', kwargs={'pk': item.pk})

class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = [
        'delivery_address',
        'products',
    ]
    filterset_fields = [
        'products',
        'delivery_address',
        'user',

    ]
    ordering_fields = [
        'pk',
        'user',
        'products'
    ]

    @action(methods=['get'], detail=False)
    def download_csv(self, request: Request):
        response = HttpResponse(content='text/csv')
        filename = 'order-export.csv'
        response['content-Disposition'] = f'attachment; filename ={filename}'
        queryset = self.filter_queryset(self.get_queryset())
        fields = [

            'delivery_address',
            'promocode',
            'user',
            'products',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()
        for order in queryset:
            writer.writerow({
                field: getattr(order, field)
                for field in fields
            })
        return response

    @action(
        detail=False,
        methods=['post'],
        parser_classes=[MultiPartParser],

    )
    def upload_csv(self, request: Request):
        orders = save_csv_products(
            request.FILES['file'].file,
            encoding=request.encoding,
        )
        serializer = self.get_serializer(orders, many=True)
        return Response(serializer.data)

class ShopIndexView(View):

    #@method_decorator(cache_page(60 * 2))
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('laptop', 1999),
            ('dekstop', 2999),
            ('smartfone', 999),
        ]

        some_list = [
            '1st cycle elem',
            'second cycle elem',
        ]
        context = {
            "time_running": default_timer(),
            "products": products,
            "some_list": some_list,
            'items': 4,
        }
        print('shop index context', context)
        log.debug('Products for shop index: %s', products)
        log.info('Rendering shop index')
        return render(request, 'shopapp/shop-index.html', context=context)


class GroupListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            'form': GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)


class ProductDetailsView(DetailView):
    template_name = 'shopapp/products-details.html'
    queryset = Product.objects.prefetch_related('images')
    context_object_name = 'product'


class ProductListViews(ListView):
    template_name = 'shopapp/products-list.html'
    #model = Product
    context_object_name = 'products'
    queryset = Product.objects.filter(archived=False)

    

class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        return self.request.user.is_superuser
    model = Product
    fields = 'name', 'price', 'description', 'discount', 'preview'
    success_url = reverse_lazy('shopapp:products_list')




class ProductUpdateView(PermissionRequiredMixin, UpdateView):

    permission_required = 'shopapp.change_product'
    model = Product
    #fields = 'name', 'price', 'description', 'discount', 'preview'
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if self.request.user.is_superuser:
            return super().dispatch(request, *args, **kwargs)
        if self.request.user.has_perm('change_product'):
            raise PermissionDenied
        if obj.created_by != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse(
            'shopapp:product_details',
            kwargs={'pk': self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist('images'):
            ProductImage.objects.create(
                product=self.object,
                image=image
            )
        return response

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('shopapp:products_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

class OrdersListView(LoginRequiredMixin,ListView):
    template_name = 'shopapp/order-list.html'
    model = Order
    context_object_name = 'orders'


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'shopapp.view_order'
    template_name = 'shopapp/order-details.html'
    model = Order
    context_object_name = 'order'

class OrderCreateView(CreateView):
    model = Order
    fields = 'delivery_address', 'promocode', 'user', 'products'
    success_url = reverse_lazy('shopapp:orders_list')


class OrderUpdateView(UpdateView):
    model = Order
    fields = 'delivery_address', 'promocode', 'user', 'products'

anothersite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        Base Title
      {% endblock %}
    </title>
</head>
<body>

 {% block body %}
    Base body
 {% endblock %}

<div>
    {% now 'H:i'%}
</div>

<div>
    {% now 'l' as current_weekday %}
     {% translate 'Today is ' %}{{ current_weekday }}
</div>


</body>
</html>

anothersite/shopapp/templates/shopapp/order-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
   Order #{{ object.pk }} details
{% endblock %}

{% block body %}
   <h1>Order #{{ object.pk }}</h1>
      <div>

            <p>Order by {% firstof object.user.first_name order.user.username %}</p>
            <p>Promocode: <code>{{object.promocode}}</code></p>
            <p>Delivery address: {{object.delivery_address}}</p>
            <div>
               Products in order:
               <ul>
               {% for product in object.products.all %}
               <li>{{ product.name }} for{{ product.price }}</li>
               {% endfor %}
               </ul>
         </div>

       </div>
   <div>
     <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
   </div>
   <div>
         <a href="{% url 'shopapp:order_delete' pk=order.pk %}">Delete order</a>
      </div>
       <div>
         <a href="{% url 'shopapp:order_update' pk=order.pk %}">Update order </a>
      </div>
{% endblock %}

anothersite/shopapp/templates/shopapp/order-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
   Orders list
{% endblock %}

{% block body %}
   <h1>Orders:</h1>
   {% if object_list %}
      <div>
         {% for order in object_list %}
         <div>
            <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
            >Details #{{ order.pk }}</a></p>
            <p>Order by {% firstof order.user.first_name order.user.username %}</p>
            <p>Promocode: <code>{{order.promocode}}</code></p>
            <p>Delivery address: {{order.delivery_address}}</p>
            <div>
               Products in order:
               <ul>
               {% for product in order.products.all %}
               <li>{{ product.name }} for{{ product.price }}</li>
               {% endfor %}
               </ul>
         </div>
          {% endfor %}
      </div>
   {% else%}
    <h3>No orders yet</h3>
   {%  endif %}
         <div>
      <a href="{% url 'shopapp:order_create' %}">
         Create a new Order</a>

   </div>
{% endblock %}

anothersite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}>

{% block title %}
   Confirm delete order
{% endblock %}

{% block body %}
   <h1>Are you sure want to delete order created at: {{ object.created_at }}? </h1>
   <br>
   <div>
       <a href="{% url 'shopapp:order_details' pk=object.pk %}">
           Back to order</a>
   </div>
   <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            Delete
        </button>
    </form>
   </div>
{% endblock %}

anothersite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}>

{% block title %}
   Create order
{% endblock %}

{% block body %}
   <h1>Create a new order</h1>
   <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Create order
        </button>
    </form>
   </div>
       <a href="{% url 'shopapp:orders_list' %}">
         Back to order list </a>

   </div>

{% endblock %}

anothersite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}>

{% block title %}
   Update order
{% endblock %}

{% block body %}
   <h1>Update order</h1>
   <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            Update
        </button>
    </form>
   </div>
   <div>
      <a href="{% url 'shopapp:order_details' pk=object.pk %}">
         Back to order #{{object.pk}} </a>

   </div>
{% endblock %}

anothersite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}

 <li>
     <a href="{% url 'admin:import_orders_csv' %}" class='addlink'>
         Import CSV
     </a>
 </li>
{{ block.super }}
{% endblock %}

anothersite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}>

{% block title %}
   Confirm archived {{ object.name }}
{% endblock %}

{% block body %}
   <h1>Are you sure want to archive this beautiful {{ object.name }}?</h1>
   <br>
   <div>
       <a href="{% url 'shopapp:product_details' pk=object.pk %}">
           Back to product</a>
   </div>
   <div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            Archive
        </button>
    </form>
   </div>
{% endblock %}

anothersite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}>

{% block title %}
   Create product
{% endblock %}

{% block body %}
   <h1>Create a new product</h1>
   <div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            Create
        </button>
    </form>
   </div>
   <div>
      <a href="{% url 'shopapp:products_list' %}">
         Back to products list </a>

   </div>
{% endblock %}

anothersite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
  {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
   <h1>{% translate 'Product ' %}<strong>{{ product.name }}</strong></h1>
   <div>
      <div>{% translate 'Description' %}:<em>{{ product.description }}</em></div>
      <div>{% translate 'Price' %}: {{ product.price }}</div>
      <div>{% translate 'Discount' %}: {{ product.discount }}</div>
      <div>{% translate 'Archived' %}: {{ product.archived }}</div>
       {% if product.preview %}
              <img src = '{{ product.preview.url }}' alt="{{ product.preview.name }}">
            {% endif %}
       <div>
     {% blocktranslate count image_count=product.images.all|length %}
        There is only one images.
        {% plural %}
        There are {{ image_count }} images.
     {% endblocktranslate %}
   </div>
       <div>
           {%for image in product.images.all %}

           <div>
               <img src = '{{ image.image.url }}' alt="{{ image.image.name }}">
               <div>{{ image.description }}</div>
           </div>
           {% empty %}
           {% blocktranslate %}
           <div>No images uploaded yet</div>
           {% endblocktranslate %}
           {% endfor %}
       </div>
      <div>
         <a href="{% url 'shopapp:products_list' %}">{% translate 'Back to products list' %}</a>
      </div>
       <div>
         <a href="{% url 'shopapp:product_delete' pk=product.pk %}">{% translate 'Archived product' %}</a>
      </div>
       <div>
         <a href="{% url 'shopapp:product_update' pk=product.pk %}">{% translate 'Update product' %}</a>
      </div>
   </div>
{% endblock %}

anothersite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}
{% load i18n %}

{% block title %}
   {% translate 'Products list' %}
{% endblock %}

{% block body %}
   <h1>{% translate 'Products' %}:</h1>
   {% if products %}
   <div>
     {% blocktranslate count products_count=products|length %}
        There is only one product.
        {% plural %}
        There are {{ products_count }} products.
     {% endblocktranslate %}
   </div>
      <div>
         {% for product in products %}
         <div>
            <p><a href="{% url 'shopapp:product_details' pk=product.pk %}"
            >{% translate 'Name' context 'product name' %}: {{ product.name }}</a></p>
            <p>{% translate 'Price'  %}: {{product.price}}</p>
            {% translate 'no discount' as no_discount %}
            <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
            {% if product.preview %}
              <img src = '{{ product.preview.url }}' alt="{{ product.preview.name }}">

            {% endif %}
         </div>
          {% endfor %}
      </div>
  <div>
      <a href="{% url 'shopapp:product_create' %}">
         {% translate 'Create a new Product' %} </a>
   </div>
   {% else%}
   {% url 'shopapp:product_create' as create_product_url%}
     {% blocktranslate %}
    <h3>No product yet</h3>
    <a href="{{ create_product_url }}"
    >Create a new one</a>
     {% endblocktranslate %}
   {%  endif %}
{% endblock %}

anothersite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
 <li>
     <a href="{% url 'admin:import_products_csv' %}">
         Import CSV
     </a>
 </li>
{{ block.super }}
{% endblock %}

anothersite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}
{%load cache %}

{% block title %}
  Shop Index
{% endblock %}


{% block body %}
  <h1> Hello Shop Index</h1>

  <div>
      <ul>
          {% for name, price in products %}
            <li>{{name|capfirst}} for {{price}}</li>
            {% if name|length_is:'7' %}
              <span>Lucky product!</span>
            {% endif %}
            {% if price < 1000 %}
                  low price!
            {% endif %}
          {% empty %}
             No items
          {% endfor %}
      </ul>
  </div>
   <div>
       <strong>
           You have {{ items }} cherr{{ items|pluralize:'y,ies' }}
       </strong>
   </div>
  <div>

      {% if products %}
         total product: {{ products|length }}
      {% else %}
         No product now
      {% endif %}

  </div>

  <div>
    Time running: {{ time_running }}
  </div>
   {% cache 100 lorem products %}
  <div>
    {% lorem 3 p random%}
  </div>
    {% endcache %}

{% endblock %}

anothersite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}
{%load cache %}

{% block title %}
    User orders
{% endblock %}

{% block body %}
<h1>Orders:</h1>
   {% if object_list %}
   <div>
       {{ owner.username }} has {{ object_list|length }} orders:
       {% cache 100 owner_orders owner.id %}
      {% for order in object_list %}
        <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details #{{ order.pk }}</a></p>
        <p>Order by {% firstof order.user.first_name order.user.username %}</p>
        <p>Promocode: <code>{{ order.promocode }}</code></p>
        <p>Delivery address: {{ order.delivery_address }}</p>
        <div>
           Products in order:
           <ul>
           {% for product in order.products.all %}
           <li>{{ product.name }} for {{ product.price }}</li>
           {% endfor %}
           </ul>
       </div>
      {% endfor %}
       {% endcache %}
   </div>
   {% else %}
    {{ owner.username }} has no orders yet
   {% endif %}
{% endblock %}